### ISSUE TITLE
Clarity should have an easy getting started guide

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/clarity#39]
I as a user, have no idea how to setup and use Clarity in my own project, it would be appreciated to have a guide for how to import and use clarity.

Rustdoc would also be nice. 

deadline: 10/14/18

**Comment by mpapierski** [comment]
I'm starting with adding rustdoc comments where it is possible. Its quite easy as its just a matter of `//!` comments and a proper markdown. I'll focus on adding sections for usage. Rustdoc also encourages "doctests" so perhaps well described code snippets could be added there.

**Comment by jkilpatr** [comment]
I am reassigning this to Stan who's job is to bother Michael until this is done. 

Stan will
review this https://github.com/althea-mesh/clarity/pull/40
write a new readme with an easy example of how to use clarity
write some documentation for Crates.io (beyond just the rustdoc)

The goal is that Michael does minimal documentation and Stan asks Michael as needed and writes down what he learns.

**Comment by mpapierski** [comment]
Just a notes:

> write some documentation for Crates.io (beyond just the rustdoc)

Crates.io uses README.md to render the document + takes `bades` entries from `Cargo.toml`. What we want to do is to also add additional badges to `Cargo.toml` for `docs.rs`.

So a solid README + badges entries should fit into all services
