### ISSUE TITLE
Remove or repurpose `PrivateKey::new`

### ISSUE THREAD

**Issue by drozdziak1** [althea-mesh/clarity#43]
# What?
Currently the `new` method in `PrivateKey` creates a private key of `0x0000[...]`. Mind you that the bytes of the key cannot be changed with any other method (which is good in itself, bugs resulting from accidentally altering a private key sound hideous and I don't think we should allow for them).

# Why?
* People assuming `new` creates a key using sane defaults might quickly find out we don't the hard way (ETH addresses are deterministically based off the public key which in turn has a deterministic relationship with the private key space) by e.g. putting money in a wallet created with `0x0000[...]`. Luckily enough `secp256k1` signing code gets upset by this. For now.
* A `new` method that doesn't yield a correct object is objectively useless. 

# What to do instead?
* Turn `from_bytes` into `new` and let people specify the bytes that way
* Remove `new` (easiest)
* Make `new` generate a random key and implement the `rand::Rand` trait while we're at it (most convenient for the user and what I would do)

**Comment by mpapierski** [comment]
One purpose for a key made of `0x00` would be when you could manipulate `PrivateKey` as a byte array - probably with a `Deref` trait (or something more explicit with slicing traits etc?) so operations such as `let key = PrivateKey::default(); key[0] = 0xffu8;` make sense. Then there are math operations for `PrivateKey` defined in secp256k1 library such as "add" or "mul" or "negate" (https://github.com/bitcoin-core/secp256k1/blob/314a61d72474aa29ff4afba8472553ad91d88e9d/src/secp256k1.c#L525, https://github.com/bitcoin-core/secp256k1/blob/314a61d72474aa29ff4afba8472553ad91d88e9d/src/secp256k1.c#L451, https://github.com/bitcoin-core/secp256k1/blob/master/src/secp256k1.c#L525) which user might want to use after creating null (or "invalid") private key.

I agree that `new()` doesn't make sense at all (is it really new key if its invalid and you can't manipulate it?), when `Default` trait can be used for creating `0x00` key along with additional operators and slicing traits to manipulate it.

IMO generating random PrivateKey using rand::Rand might be different (additional) feature to implement. It could be mentioned that for now you can do it by just filling up an array yourself and call appropriate From trait.

**Comment by jkilpatr** [comment]
make it generate from rand.
