### ISSUE TITLE
Add deserialization methods for `Signature`

### ISSUE THREAD

**Issue by drozdziak1** [althea-mesh/clarity#47]
Currently `Signature` serializes okay with the custom big-endian vec method, but `serde` assumes it's going to deserialize three `Uint256`'s. @mpapierski Why does it have custom serialization and is it really needed?

**Comment by mpapierski** [comment]
@drozdziak1 thats right, it is necessary for binary serialization using serde-rlp for the purpose of generating transaction data. I just implemented a from_str/from_bytes helpers for Signature which might make it easier to serialize/deserialize signatures manually. Check out changes in  4e3dd06d5c52942993d5b102c0695b29b4ca0505
