### ISSUE TITLE
Implement Serialize and Deserialize such that Serde produces and handles strings

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/clarity#53]
If we just derive serialize and de serialize then we're going to get a really bulky series of chars in our config files

{[24, 56, ....]} 

This presents two problems.

A) it's annoying to deal with existing values in those fields (string representations) they cause serde to crash so we need to at minimum implement a handler to throw them away or rename the fields. Both a pain

B) if anyone has a key they generated themselves they may want to set it in the config file, which will presently be an unreadable mess

Implementing serialize and de-serialize traits to use the string representation by default solves these issues. 

Being able to handle various arrays (u8, u16, u32, u64, u128) as well as the other valid formats would be a bonus.

**Comment by jtremback** [comment]
Yes please!
